# Generated by Django 2.1.3 on 2018-11-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181103_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
